
x_max : 1.6
x_min : -1.1
y_max : 1.08
y_min : -0.99 

x_max_offset : 0.3
x_min_offset : 0.2
y_max_offset : 0.2
y_min_offset : 0.2

corner_factor : 0.5

lidar_safe_dist : 0.20

shift_goal : 0.2

front_angle : 180
clearance : 120



